apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - image: prom/alertmanager
          name: alertmanager
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: alertmanager-persistent-storage
            mountPath: /etc/alertmanager/alertmanager.yml
      volumes:
      - name: alertmanager-persistent-storage
        hostPath:
          path: /usr/local/alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    app: alertmanager
spec:
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: alertmanager