kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbit-cluster
  name: rabbit-cluster
  namespace: default
spec:
  ports:
  - name: amqp1
    port: 5671
  - name: amqp2
    port: 5672
  - name: epmd
    port: 4369
  - name: management
    port: 15672
  clusterIP: None
  selector:
    app: rabbit-cluster
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbit-cluster
  name: rabbit-cluster-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - name: amqp1
    port: 5671
    nodePort: 30671
  - name: amqp2
    port: 5672
    nodePort: 30672
  selector:
    app: rabbit-cluster
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rabbitmq
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: rabbit
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbit-cluster
                port:
                  number: 15672