kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbit-cluster
  name: rabbit-cluster
  namespace: default
spec:
  ports:
  - name: amqp1
    port: 5671
  - name: amqp2
    port: 5672
  - name: epmd
    port: 4369
  clusterIP: None
  selector:
    app: rabbit-cluster
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbit-cluster
  name: rabbit-cluster-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - name: management
    port: 15672
    nodePort: 30671
  selector:
    app: rabbit-cluster