kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rocket-exporter
  name: rocket-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocket-exporter
  template:
    metadata:
      name: rocket-exporter
      labels:
        app: rocket-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "5557"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - rocket-exporter
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: rocket-exporter
        image: repository:5000/rocketmq-exporter
        imagePullPolicy: Always
        args: ["--rocketmq.config.namesrvAddr=rocket-namesrv:9876"]
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rocket-exporter
  name: rocket-exporter
  namespace: default
spec:
  ports:
  - port: 5557
    targetPort: 5557
  selector:
    app: rocket-exporter
