apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.126.com:465' 
      smtp_from: 'fangang2004@126.com'
      smtp_auth_username: 'fangang2004@126.com'
      smtp_auth_password: 'GJJOSXBXZFLTNRZX'
      smtp_require_tls: false
    route:
      group_by: ['alertname']
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 5m
      receiver: webhook
      routes:
      - receiver: 'email'
        group_wait: 10s
        match:
          alertname: email_alert
      - receiver: 'webhook'
        group_wait: 10s
        match:
          alertname: webhook_alert
    receivers:
    - name: email
      email_configs:
      - to: 'fangang2004@126.com'
    - name: webhook
      webhook_configs:
      - url: http://dingtalk:8060/dingtalk/webhook1/send
        send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - image: prom/alertmanager
        name: alertmanager
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: alertmanager-conf
          mountPath: /etc/alertmanager
      volumes:
      - name: alertmanager-conf
        configMap:
          name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    app: alertmanager
spec:
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: alertmanager