kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "9121"
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /data
        - name: redis-exporter
          image: oliver006/redis_exporter
          ports:
            - containerPort: 9121
      volumes:
        - name: data
          hostPath:
            path: /etc/redis

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: redis
  name: redis
  namespace: default
spec:
  ports:
    - name: http
      port: 6379
  clusterIP: None
  selector:
    app: redis

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: redis
  name: redis-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 6379
      targetPort: 6379
      nodePort: 31379
  selector:
    app: redis