kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-configmap
  namespace: default
  labels:
    app: redis-cluster
data:
  redis.conf: |-
    appendonly yes
    cluster-enabled yes
    cluster-config-file /etc/redis/nodes.conf
    cluster-node-timeout 5000
    dir /etc/redis
    port 6379





