kind: ConfigMap
apiVersion: v1
metadata:
  name: metricbeat-config
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression
    setup.dashboards.enabled: true
    output.elasticsearch:
      hosts: ["http://elasticsearch-logging-0.elasticsearch-logging:9200"]
    setup.kibana:
      host: "http://kibana-logging.kube-system:5601"
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~

    metricbeat.modules:
    - module: system
      enabled: true
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - socket_summary
        - core
        - diskio
        - socket
      process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory

    - module: system
      enabled: true
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

    - module: system
      enabled: true
      period: 15m
      metricsets:
        - uptime

    #- module: system
    #  period: 5m
    #  metricsets:
    #    - raid
    #  raid.mount_point: '/'

  kubernetes.yml: |-
    - module: kubernetes
      enabled: true
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      hosts: ["172.31.87.109:31100","172.31.87.110:31100","172.31.87.111:31100"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #ssl.certificate_authorities:
      #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      #username: "user"
      #password: "secret"

      # Enriching parameters:
      #add_metadata: true
      #in_cluster: true
      #labels.dedot: true
      #annotations.dedot: true
      # When used outside the cluster:
      #in_cluster: false
      #host: node_name
      #kube_config: ~/.kube/config

    # State metrics from kube-state-metrics service:
    #- module: kubernetes
    #  metricsets:
    #    - state_node
    #    - state_deployment
    #    - state_replicaset
    #    - state_statefulset
    #    - state_pod
    #    - state_container
    #  period: 10s
    #  hosts: ["kube-state-metrics:8080"]
    #  add_metadata: true
    #  in_cluster: true

    # Kubernetes events
    #- module: kubernetes
    #  metricsets:
    #    - event