kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        imagePullPolicy: Always
        ports:
        - containerPort: 15692
          name: prometheus
        volumeMounts: 
         - name: data
           mountPath: /var/lib/rabbitmq
      volumes:
      - name: data
        hostPath:
          path: /var/lib/rabbitmq
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  ports:
  - name: amqp1
    port: 5671
  - name: amqp2
    port: 5672
  - name: epmd
    port: 4369
  - name: management
    port: 15672
  clusterIP: None
  selector:
    app: rabbitmq
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-svc
  namespace: default
spec:
  type: NodePort
  ports:
  - name: amqp1
    port: 5671
    nodePort: 31671
  - name: amqp2
    port: 5672
    nodePort: 31672
  selector:
    app: rabbitmq
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rabbitmq
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: rabbit
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672