groups:
  - name: kubernetes-resources.rules
    rules:
    - alert: pod_memory_limits #pod memory limits
      annotations:
        message: '{{`{{ $labels.pod_name }}`}}  10 min current  limits memory usage {{`{{ $value }}`}}%'
      expr: |-
        sum by(pod_name,namespace,node) 
        (label_join(container_memory_working_set_bytes{}, "pod_name", "___", "pod_name", "container_name"))
        /  
        sum by(pod_name,namespace,node) 
        (label_join(kube_pod_container_resource_limits_memory_bytes{}, "pod_name", "___", "pod", "container")) 
        * 100 > 90
      for: 10m
      labels:
        severity: critical
    - alert: pod_cpu_limits #pod cpu limits
      annotations:
        message: '{{`{{ $labels.pod_name }}`}} 10 min current  limits cpu usage {{`{{ $value }}`}}%'
      expr: |-
        sum(label_join(rate(container_cpu_usage_seconds_total{}[5m]),"pod_name","___","pod_name","container_name")) 
        by (pod_name,namespace,node) 
        /
        sum(label_join(kube_pod_container_resource_limits_cpu_cores{},"pod_name","___","pod","container")) 
        by (pod_name,namespace,node) 
        * 100 > 90
      for: 10m
      labels:
        severity: critical
    - alert: KubePersistentVolumeUsageCritical
      annotations:
        message: The PersistentVolume claimed by {{`{{ $labels.persistentvolumeclaim }}`}}  only {{`{{ printf "%0.2f" $value }}`}}% free.
      expr: |-
        100 * kubelet_volume_stats_available_bytes{job="kubelet"}
          /
        kubelet_volume_stats_capacity_bytes{job="kubelet"}
          < 3
      for: 1m
      labels:
        severity: critical
    - alert: KubePersistentVolumeFullInFourDays
      annotations:
        message: Based on recent sampling, the PersistentVolume claimed by {{`{{ $labels.persistentvolumeclaim }}`}}  is expected to fill up within four days. Currently {{`{{ printf "%0.2f" $value }}`}}% is available.
      expr: |-
        100 * (
          kubelet_volume_stats_available_bytes{job="kubelet"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet"}
        ) < 15
        and
        predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0
      for: 5m
      labels:
        severity: critical
    - alert: KubePersistentVolumeErrors
      annotations:
        message: The persistent volume {{`{{ $labels.persistentvolume }}`}} has status {{`{{ $labels.phase }}`}}.
      expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kube-state-metrics"} > 0
      for: 5m
      labels:
        severity: critical