apiVersion: v1
kind: Service
metadata:
  name: hadoop-slave
  namespace: bigdata
spec:
  ports:
  - port: 8040
    name: yarn-slave
  - port: 8081
    name: spark-worker
  selector:
    app: hadoop-slave
  clusterIP: None