global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['172.31.87.109:31100','172.31.87.110:31100','172.31.87.111:31100']
        labels: 
          group: 'client-node-exporter'
      - targets: ['172.31.87.111:9091']
        labels:
          group: 'pushgateway'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['172.31.87.111:9003']